version: '3'
services:
 elasticsearch:
  image: bolingcavalry/elasticsearch-with-ik:6.5.0
  container_name: elasticsearch
  environment:
   - cluster.name=docker-cluster
   - bootstrap.memory_lock=true
   - http.cors.enabled=true
   - http.cors.allow-origin=*
   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
   memlock:
    soft: -1
    hard: -1
   nofile:
     soft: 65536
     hard: 65536
  restart: always
  volumes:
   - /docker/data/elasticsearch:/usr/share/elasticsearch/data
  ports:
   - 9200:9200
  networks:
   - esnet
 elasticsearch2:
  image: bolingcavalry/elasticsearch-with-ik:6.5.0
  container_name: elasticsearch2
  environment:
   - cluster.name=docker-cluster
   - bootstrap.memory_lock=true
   - http.cors.enabled=true
   - http.cors.allow-origin=*
   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   - "discovery.zen.ping.unicast.hosts=elasticsearch"
  ulimits:
   memlock:
    soft: -1
    hard: -1
   nofile:
    soft: 65536
    hard: 65536
  restart: always
  volumes:
   - /docker/data/elasticsearch:/usr/share/elasticsearch/data
  networks:
   - esnet
 head:
  image: bolingcavalry/elasticsearch-head:6
  container_name: head
  ports:
   - 9100:9100
  networks:
   - esnet
volumes:
 esdata1:
  driver: local
 esdata2:
  driver: local

networks:
 esnet: