version: '3'
services:
 elasticsearch:
  image: bolingcavalry/elasticsearch-with-ik:6.5.0
  container_name: elasticsearch
  environment:
   - bootstrap.memory_lock=true
   - ES_JAVA_OPTS=-Xms512m -Xmx512m
   - discovery.type=single-node
   - TAKE_FILE_OWNERSHIP=true
   - http.cors.enabled=true
   - http.cors.allow-origin=*
   - ES_JAVA_OPTS=-Xms218m -Xmx218m
  ulimits:
   memlock:
    soft: -1
    hard: -1
  restart: always
  volumes:
   - /docker/data/elasticsearch:/usr/share/elasticsearch/data
  ports:
   - 9200:9200
 head:
  image: bolingcavalry/elasticsearch-head:6
  container_name: head
  ports:
   - 9100:9100