version: '3'

services:
  php:
    container_name: php
    image: registry.cn-beijing.aliyuncs.com/duiying/php7.2:1.0
    tty: true
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www:/data/www
      - ./docker/log/php:/var/log/php-fpm
    depends_on:
      - mysql
      - redis
    links:
      - mysql:mysql
      - redis:redis
  nginx:
    container_name: nginx
    image: registry.cn-beijing.aliyuncs.com/duiying/nginx:1.0
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/data/www
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/log/nginx:/var/log/nginx
    depends_on:
      - php
    links:
      - php:php
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:5.7
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    container_name: redis
    image: daocloud.io/library/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    command: redis-server --appendonly yes
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - ./docker/data/elasticsearch:/usr/share/elasticsearch/data
      - ./docker/config/elasticsearch:/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    head:
      container_name: head
      image: mobz/elasticsearch-head:5
      ports:
        - "9100:9100"
      depends_on:
        - elasticsearch
      links:
        - elasticsearch:elasticsearch